// AUTO-GENERATED by "npm run gen_mathtests".
// Do not edit manually.

import { describe, expect, it } from "vitest";
import {
  buildAssertions,
  parseFixture,
  replayEvents,
  ROOT_DIR,
} from "../../scripts/mathtestReplay";

describe("mathtest fixtures", () => {
  it("can_deselect_in_blank_space", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_deselect_in_blank_space.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("can_double_click_select_fraction", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_double_click_select_fraction.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("can_mult_select_in_sum", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_mult_select_in_sum.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });


  it("can_select_a_different_thing", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_select_a_different_thing.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("can_select_item_in_sum", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_select_item_in_sum.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("can_select_numerator", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_select_numerator.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("can_select_whole_sum_from_frac", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/can_select_whole_sum_from_frac.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });


  it("do_not_deselect_on_clicking_equals", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/do_not_deselect_on_clicking_equals.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("double_click_selects_sum", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/double_click_selects_sum.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });


  it("plus_sign_not_selectable", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/plus_sign_not_selectable.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

  it("rejects_multi_selection_on_rhs", async () => {
    const fixture = await parseFixture(`${ROOT_DIR}/mathtests/fixtures/rejects_multi_selection_on_rhs.json`);
    const replayResult = replayEvents(fixture);
    const failures = buildAssertions(fixture, replayResult);
    expect(failures).toEqual([]);
  });

});
