import { stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { FIXTURE_DIR, ROOT_DIR, walkJsonFiles } from "./mathtestReplay";

const OUTPUT_FILE = path.join(ROOT_DIR, "src", "mathtests", "fixtureReplay.test.ts");

function fixtureNameFromPath(filePath: string): string {
  const relative = path.relative(FIXTURE_DIR, filePath);
  const withoutExt = relative.replace(/\.json$/i, "");
  return withoutExt.replace(/[\\/]+/g, "__");
}

function buildTestFile(fixtureFiles: string[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED by "npm run gen_mathtests".',
    "// Do not edit manually.",
    "",
    'import { describe, expect, it } from "vitest";',
    "import {",
    "  buildAssertions,",
    "  parseFixture,",
    "  replayEvents,",
    "  ROOT_DIR,",
    '} from "../../scripts/mathtestReplay";',
    "",
    'describe("mathtest fixtures", () => {',
  ];

  for (const filePath of fixtureFiles) {
    const relativeToRoot = path.relative(ROOT_DIR, filePath).replace(/\\/g, "/");
    const fixtureName = fixtureNameFromPath(filePath);
    lines.push(`  it("${fixtureName}", async () => {`);
    lines.push(`    const fixture = await parseFixture(\`\${ROOT_DIR}/${relativeToRoot}\`);`);
    lines.push("    const replayResult = replayEvents(fixture);");
    lines.push("    const failures = buildAssertions(fixture, replayResult);");
    lines.push("    expect(failures).toEqual([]);");
    lines.push("  });");
    lines.push("");
  }

  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const fixtureDirStat = await stat(FIXTURE_DIR);
  if (!fixtureDirStat.isDirectory()) {
    throw new Error(`Fixture directory path is not a directory: ${FIXTURE_DIR}`);
  }

  const fixtureFiles = (await walkJsonFiles(FIXTURE_DIR)).sort((a, b) =>
    path.relative(FIXTURE_DIR, a).localeCompare(path.relative(FIXTURE_DIR, b)),
  );

  if (fixtureFiles.length === 0) {
    throw new Error(`No fixture JSON files found in ${FIXTURE_DIR}.`);
  }

  const output = buildTestFile(fixtureFiles);
  await writeFile(OUTPUT_FILE, output, "utf8");
  console.log(
    `Generated ${path.relative(ROOT_DIR, OUTPUT_FILE)} with ${fixtureFiles.length} tests.`,
  );
}

void main();
