import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const iconDirectory = path.join(repositoryRoot, "public", "icons");
const outputPath = path.join(
  repositoryRoot,
  "src",
  "mathEntry",
  "generatedMacroIconSvg.ts",
);

const icons = [
  ["derivativeIconSvg", "derivative.svg"],
  ["derivativeOperatorIconSvg", "derivative-operator.svg"],
  ["definiteIntegralIconSvg", "definite-integral.svg"],
  ["indefiniteIntegralIconSvg", "indefinite-integral.svg"],
  ["partialDerivativeIconSvg", "partial-derivative.svg"],
  ["partialDerivativeOperatorIconSvg", "partial-derivative-operator.svg"],
  ["partialDerivativeSubscriptIconSvg", "partial-derivative-subscript.svg"],
];

const exports = await Promise.all(
  icons.map(async ([exportName, fileName]) => {
    const svg = await readFile(path.join(iconDirectory, fileName), "utf8");
    return `export const ${exportName} = ${JSON.stringify(svg)};`;
  }),
);

await writeFile(
  outputPath,
  [
    "// Generated by scripts/generateMacroIconModule.mjs.",
    "// Edit the source SVG files in public/icons, then rebuild the UI package.",
    "",
    ...exports,
    "",
  ].join("\n"),
  "utf8",
);
