import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const repositoryRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const materialIconDirectory = path.join(
  repositoryRoot,
  "node_modules",
  "@material-symbols",
  "svg-400",
  "rounded",
);
const outputPath = path.join(
  repositoryRoot,
  "src",
  "icons",
  "generatedUiIconSvg.ts",
);

const materialIconNames = [
  "arrow_downward",
  "arrow_drop_down",
  "arrow_upward",
  "calculate",
  "call_split",
  "check",
  "content_copy",
  "data_array",
  "data_object",
  "delete",
  "edit",
  "exposure_neg_1",
  "function",
  "functions",
  "history",
  "input",
  "ramp_left",
  "rule",
  "select_all",
  "vertical_align_bottom",
];

const entries = await Promise.all(
  materialIconNames.map(async (name) => [
    name,
    await readFile(path.join(materialIconDirectory, `${name}.svg`), "utf8"),
  ]),
);
entries.push([
  "clean",
  await readFile(
    path.join(repositoryRoot, "public", "icons", "clean.svg"),
    "utf8",
  ),
]);

await writeFile(
  outputPath,
  [
    "// Generated by scripts/generateUiIconModule.mjs.",
    "// Edit the source icon list or SVG files, then rebuild the UI package.",
    "",
    `export const UI_ICON_SVG = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const;`,
    "",
    "export type UiIconName = keyof typeof UI_ICON_SVG;",
    "",
  ].join("\n"),
  "utf8",
);
